### PR TITLE
Key F12 is not global anymore

### PR DESCRIPTION
**Pull request by lzap**
One more thing, it actually does not work. The key is still reconfigured by
default, the configuration must be renamed for Windows only. Sorry about that
:-(

### CODE REVIEW

**Comment by damccull** [comment]
I don't understand. Can you reword your comment?

**Comment by lzap** [comment]
You currently override the F12 key (which is by default on Linux/MacOS defined to Go To Symbol) in `Default.sublime-keymap`. This file isn't overridable, thus this should be moved to `Default (Windows).sublime-keymap`. The F12 key is "free" only on Windows I believe.

**Comment by lzap** [comment]
In other words - my latest patch does only provide Ctrl+F12, which is nice, but the reason why I submitted that was to be able to use F12 (which is still redefined).

**Comment by damccull** [comment]
I understand now. Good catch. I'll merge this.

**Pull request merged**
